ZRAM_SRC = zram-5.4
EXTRA_CFLAGS += -DCONFIG_ZRAM_5_4

# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(srctree)/$(src)/../../include

ifneq ($(filter m y,$(CONFIG_HYBRIDSWAP_ZRAM)),)
EXTRA_CFLAGS += -DCONFIG_HYBRIDSWAP_ZRAM
endif

ifneq ($(filter m y,$(CONFIG_HYBRIDSWAP_ZRAM_WRITEBACK)),)
EXTRA_CFLAGS += -DCONFIG_HYBRIDSWAP_ZRAM_WRITEBACK
endif

ifneq ($(filter m y,$(CONFIG_HYBRIDSWAP)),)
EXTRA_CFLAGS += -DCONFIG_HYBRIDSWAP
endif

ifneq ($(filter m y,$(CONFIG_HYBRIDSWAP_SWAPD)),)
EXTRA_CFLAGS += -DCONFIG_HYBRIDSWAP_SWAPD
endif

ifneq ($(filter m y,$(CONFIG_HYBRIDSWAP_CORE)),)
EXTRA_CFLAGS += -DCONFIG_HYBRIDSWAP_CORE
endif

zram-objs += $(ZRAM_SRC)/zram_drv.o
zram-objs += hybridswap/hybridswap_main.o
zram-objs += hybridswap/hybridswap_eswap.o

zram-objs += hybridswap/hybridswap_swapd.o
zram-objs += $(ZRAM_SRC)/zcomp.o

# Named "zram" so /sys/module/zram and its parameters exist for
# userspace/kernel-manager detection.
obj-$(CONFIG_HYBRIDSWAP_ZRAM) += zram.o
